import {
  VaseIcon,
  CarnationIcon,
  SoilIcon,
  DecorIcon,
  LeafIcon,
  PlantIcon,
  BasketIcon,
  LilyIcon,
  ToyIcon,
  NewYearIcon,
  CardIcon,
  PeonyIcon,
  RoseIcon,
  TulipIcon,
  ChrysanthemumIcon,
  AcsessoriesIcon,
  TaraIcon,
  DefaultIcon
} from "../icons/index";

export const priceCategoriesConfig = [
  { key: "ЦВЕТЫ КИТАЙ", icon: PeonyIcon, order: 1 },
  { key: "ГВОЗДИКА", icon: CarnationIcon, order: 2 },
  { key: "ЗЕЛЕНЬ", icon: LeafIcon, order: 3 },
  { key: "ЛИЛИЯ", icon: LilyIcon, order: 4 },
  { key: "ПИОНЫ", icon: PeonyIcon, order: 5 },
  { key: "РАЗНОЕ", icon: PeonyIcon, order: 6 },
  { key: "РОЗА МЕСТНАЯ", icon: RoseIcon, order: 7 },
  { key: "РОЗА НА ВОДЕ", icon: RoseIcon, order: 8 },
  { key: "РОЗА КУСТОВАЯ НА ВОДЕ", icon: RoseIcon, order: 9 },
  { key: "РОЗА КЕНИЯ", icon: RoseIcon, order: 10 },
  { key: "РОЗА КЕНИЯ КУСТОВАЯ", icon: RoseIcon, order: 11 },
  { key: "РОЗА ЭКВАДОР", icon: RoseIcon, order: 12 },
  { key: "СУХОЦВЕТЫ", icon: PeonyIcon, order: 13 },
  { key: "ТЮЛЬПАНЫ", icon: TulipIcon, order: 14 },
  { key: "ХРИЗАНТЕМА", icon: ChrysanthemumIcon, order: 15 },
  { key: "КОМНАТНЫЕ  РАСТЕНИЯ", icon: PlantIcon, order: 16 },
  { key: "КОМНАТНЫЕ КИТАЙ", icon: PlantIcon, order: 17 },
  { key: "УПАКОВКА", icon: AcsessoriesIcon, order: 18 },
  { key: "ВАЗЫ И КЕРАМИКА", icon: VaseIcon, order: 19 },
  { key: "ГРУНТ И УДОБРЕНИЯ", icon: SoilIcon, order: 20 },
  { key: "ДЕКОР", icon: DecorIcon, order: 21 },
  { key: "КОРЗИНА", icon: BasketIcon, order: 22 },
  { key: "МЯГКАЯ ИГРУШКА", icon: ToyIcon, order: 23 },
  { key: "НОВЫЙ ГОД", icon: NewYearIcon, order: 24 },
  { key: "ОТКРЫТКИ", icon: CardIcon, order: 25 },
  { key: "СИЛИКОНОВЫЕ ЦВЕТЫ", icon: PeonyIcon, order: 26 },
  { key: "СУХИЕ РОЗЫ", icon: PeonyIcon, order: 27 },
  { key: "ТАРА", icon: TaraIcon, order: 28 },
  { key: "СОРТОВОЙ", icon: RoseIcon, order: 29 },
];

export const DEFAULT_CATEGORY_ICON = DefaultIcon;